name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: bitnami/git
    steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'

    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Build
      run: hugo --minify

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./public
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Deploy to GitHub Pages
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        # 初始化 gh-pages 分支
        git clone --branch gh-pages --single-branch https://x-access-token:${REPO_TOKEN}@github.com/${{ github.repository }} gh-pages
        cd gh-pages
        # 清空旧内容并复制新内容
        rm -rf ./*
        cp -r ../public/* ./
        # 提交并推送
        git add --all
        git commit -m "Deploy site on $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin gh-pages --force