name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted
    env:
      TZ: Asia/Shanghai
      HUGO_ENVIRONMENT: production
    container:
      image: bitnami/git:latest

    steps:
    # 获取 hugo 最新版本号
    - name: Get Latest Hugo Version
      id: get-version
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')
        echo "version=${LATEST_VERSION}" >> $GITHUB_OUTPUT

    # 缓存
    - name: Cache Hugo
      id: cache-hugo
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/hugo
        key: hugo-${{ runner.os }}-${{ runner.arch }}-${{ steps.get-version.outputs.version }}
        restore-keys: hugo-${{ runner.os }}-${{ runner.arch }}-

    # 安装 hugo
    - name: Setup Hugo
      if: steps.cache-hugo.outputs.cache-hit != 'true'
      run: |
        curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${{ steps.get-version.outputs.version }}/hugo_${{ steps.get-version.outputs.version }}_linux-arm64.tar.gz
        tar -xzf hugo.tar.gz
        mv hugo /usr/local/bin/

    # 下载代码仓
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    # 生成静态博客
    - name: Build
      run: hugo --minify

    # 部署至 gh-page 分支
    - name: Deploy
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 配置 Git 用户信息
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # 初始化 gh-pages 分支
        rm -rf .git/
        mkdir gh-pages && cd gh-pages
        git init
        git remote add origin https://x-access-token:${REPO_TOKEN}@github.com/${{ github.repository }}.git
        git fetch origin gh-pages || echo "gh-pages branch does not exist"
        git switch gh-pages || git switch -c gh-pages

        # 清理旧内容并复制新内容
        rm -rf ./*
        cp -r ../public/* ./

        # 提交并推送
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Deploy site on $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f origin gh-pages
        else
          echo "Nothing to commit, working tree clean."
        fi