name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: alpine/git:latest
    steps:
    - name: Setup
      run: |
        doas apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community hugo

    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      run: apt install hugo

    - name: Build Hugo site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
